### ISSUE TITLE
Can a delta client request all updates since some time in the past?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#274]
Some delta clients might be interested in updates that happened during the client's absence, e.g. [auto fixer](https://github.com/LionWeb-io/specification/issues/264#issuecomment-2097741624).

Can this client ask the repository to "replay" all deltas since some time in the past?
How would it specify that time?

**Comment by joswarmer** [comment]
To make this useful, the server should that also return a "time" with each other request in the current bulk protocol. Otherwise the client does not have the information to know from which time to ask for delta.

If we support this, it will take away the necessity to return the current nodes when subscribing, because the following scenario will simply work:

1. Client requests partitions
2. Client requests full AST for partition P
3. Server returns chunk for partition P + the "time-marker"  TM at which this chunk was taken.
4. Client subscribes to partition P since TM.

**Comment by enikao** [comment]
Related to #68

**Comment by enikao** [comment]
In #294 / #295, we've decided the repository doesn't need to keep a history. This implies a client **cannot** request past updates.

This might change once we start thinking about additional APIs for #26

**Comment by enikao** [comment]
# Decision: Not for standard delta / bulk API, might be additional API

E.g. #26
